name: Compilar App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Ensamblar y compilar
        run: |
          flutter create app_generada
          cp frontend/pubspec.yaml app_generada/pubspec.yaml
          mkdir -p app_generada/lib
          cp frontend/lib/*.dart app_generada/lib/
          
          # TRUCO: El robot inyecta los permisos de GPS automáticamente
          sed -i 's/<application/<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" \/>\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" \/>\n    <application/'  app_generada/android/app/src/main/AndroidManifest.xml
          
          cd app_generada
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: APK-ViaLibre
          path: app_generada/build/app/outputs/flutter-apk/app-release.apk
